const dataWithSubRows = [
    {
        id: 1,
        firstName: 'Revising Java Script',
        lastName: 'Doe',
        age: 30,
        visits: 5,
        status: 'Active',
        progress: 50,
        subRows: [
            {
                id: 2,
                firstName: 'Variable,Data Type',
                lastName: 'Smith',
                age: 25,
                visits: 7,
                status: 'Inactive',
                progress: 70,
            },
            {
                id: 3,
                firstName: 'Functions,Control Flow',
                lastName: 'Johnson',
                age: 35,
                visits: 3,
                status: 'Active',
                progress: 30,
            },
            {
                id: 4,
                firstName: 'Object,Arrays',
                lastName: 'Johnson',
                age: 35,
                visits: 3,
                status: 'Active',
                progress: 30,
            },
            {
                id: 4,
                firstName: 'DOM Manupulation,Asynch Programming',
                lastName: 'Johnson',
                age: 35,
                visits: 3,
                status: 'Active',
                progress: 30,
            },
            {
                id: 4,
                firstName: 'Modules,Error Handling',
                lastName: 'Johnson',
                age: 35,
                visits: 3,
                status: 'Active',
                progress: 30,
            },
        ],
    },
    // {
    //     id: 4,
    //     firstName: 'Sarah',
    //     lastName: 'Williams',
    //     age: 28,
    //     visits: 10,
    //     status: 'Active',
    //     progress: 80,
    // },
    {
        id: 9,
        firstName: 'Lets find out JSX',
        lastName: 'Davis',
        age: 32,
        visits: 12,
        status: 'Inactive',
        progress: 90,
        subRows: [
            {
                id: 6,
                firstName: 'Syntax',
                lastName: 'Anderson',
                age: 29,
                visits: 8,
                status: 'Active',
                progress: 60,
            },
            {
                id: 6,
                firstName: 'Component based',
                lastName: 'Anderson',
                age: 29,
                visits: 8,
                status: 'Active',
                progress: 60,
            },
            {
                id: 6,
                firstName: 'Javascript Expression',
                lastName: 'Anderson',
                age: 29,
                visits: 8,
                status: 'Active',
                progress: 60,
            },
            {
                id: 6,
                firstName: 'Event handling,Component Composition',
                lastName: 'Anderson',
                age: 29,
                visits: 8,
                status: 'Active',
                progress: 60,
            },
            {
                id: 6,
                firstName: 'JSX and React',
                lastName: 'Anderson',
                age: 29,
                visits: 8,
                status: 'Active',
                progress: 60,
            },
        ],
    },

    {
        id: 5,
        firstName: 'Lets Dive in to React',
        lastName: 'Davis',
        age: 32,
        visits: 12,
        status: 'Inactive',
        progress: 90,
        subRows: [
            {
                id: 6,
                firstName: 'Concepts,History',
                lastName: 'Anderson',
                age: 29,
                visits: 8,
                status: 'Active',
                progress: 60,
            },
            {
                id: 6,
                firstName: 'State,Props',
                lastName: 'Anderson',
                age: 29,
                visits: 8,
                status: 'Active',
                progress: 60,
            },
            {
                id: 6,
                firstName: 'Class component,Lifecycle Method',
                lastName: 'Anderson',
                age: 29,
                visits: 8,
                status: 'Active',
                progress: 60,
            },
            {
                id: 6,
                firstName: 'Functional Component,Hooks',
                lastName: 'Anderson',
                age: 29,
                visits: 8,
                status: 'Active',
                progress: 60,
            },
            {
                id: 6,
                firstName: 'Create class component challenge',
                lastName: 'Anderson',
                age: 29,
                visits: 8,
                status: 'Active',
                progress: 60,
            },
            {
                id: 6,
                firstName: 'Create functional component challenge',
                lastName: 'Anderson',
                age: 29,
                visits: 8,
                status: 'Active',
                progress: 60,
            },
        ],
    },
    {
        id: 5,
        firstName: 'Challenges on React basic understanding',
        lastName: 'Davis',
        age: 32,
        visits: 12,
        status: 'Inactive',
        progress: 90,
        subRows: [
            {
                id: 6,
                firstName: 'Practice Exercise basic',
                lastName: 'Anderson',
                age: 29,
                visits: 8,
                status: 'Active',
                progress: 60,
            },
            {
                id: 6,
                firstName: 'Practice exercise advance',
                lastName: 'Anderson',
                age: 29,
                visits: 8,
                status: 'Active',
                progress: 60,
            },   
        
        ],
    },
    {
        id: 5,
        firstName: 'Take Assement for passing the level',
        lastName: 'Davis',
        age: 32,
        visits: 12,
        status: 'Inactive',
        progress: 90,
        subRows: [
            {
                id: 6,
                firstName: 'MCQ Question',
                lastName: 'Anderson',
                age: 29,
                visits: 8,
                status: 'Active',
                progress: 60,
            },
            {
                id: 6,
                firstName: 'Practice exercise question',
                lastName: 'Anderson',
                age: 29,
                visits: 8,
                status: 'Active',
                progress: 60,
            },   
        
        ],
    },
];

export { dataWithSubRows };
